### ISSUE TITLE
Chat client exception

### ISSUE THREAD

**Issue by nanderh** [mothran/bunny#4]
So I found another one while running the chat client, just pops up at random intervals. Afterwards the machine is able to transmit but not receive. Am only able to replicate this error on kali linux, ubuntu seems to be fine.

Exception in thread BunnyReadThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/root/bunnymk4/bunny/libbunny/bunny.py", line 203, in run
    temp = type[2].decode(encoded)
  File "/root/bunnymk4/bunny/libbunny/Templates.py", line 262, in decode
    size, = struct.unpack("B", input[26:27])
error: unpack requires a string argument of length 1

Looked at the code but having trouble to grasp whats going on.

**Comment by mothran** [comment]
So this is curious because your are getting data packets that are shorter than they should be.  I added a check for small packets in this commit: https://github.com/mothran/bunny/commit/57c0f3816626f7696b59f4b88d1ee8575220fee9

The reason it would transmit but not recv is because the thread that reads and decodes packets can crash but not take the rest of the program down currently.

If you want to give me a .pcap when while you see this that might help me make a better fix.  What is curious is that the error is not happening in Ubuntu.  Which makes me think there could be something up with your chipset. 

Hope this commit fixes it in the mean time.

**Comment by nanderh** [comment]
Ill give it another try tomorrow with the old version en get a .pcap and retry with the new commit, chipset shouldnt be the problem as I'm using identical wifi adapters on both computers. I guess we'll leave it at something odd in the OS.
